AWSTemplateFormatVersion: '2010-09-09'
Description: 'Despliegue de contenedor CRUD API desde ECR usando LabRole existente'

Parameters:
  ContainerImage:
    Type: String
    Default: 000870181791.dkr.ecr.us-east-1.amazonaws.com/crud-api-repo:latest
    Description: URI de la imagen en ECR
  LabRoleARN:
    Type: String
    Description: ARN del LabRole existente
    Default: arn:aws:iam::000870181791:role/LabRole
  VpcId:
    Type: String
    Description: ID de la VPC donde desplegar el servicio
  SubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: Lista de IDs de subredes para el servicio

Resources:
  # Cluster ECS
  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: crud-api-cluster

  # Task Definition - Usa el LabRole existente como ExecutionRoleArn
  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: crud-api-task
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      Cpu: 256
      Memory: 512
      ExecutionRoleArn: !Ref LabRoleARN  # Usa el rol existente
      ContainerDefinitions:
        - Name: crud-api-container
          Image: !Ref ContainerImage
          PortMappings:
            - ContainerPort: 80  # Puerto 80 según tu Dockerfile
              Protocol: tcp
          Essential: true
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref CloudWatchLogsGroup
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: ecs

  # Servicio ECS
  ECSService:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: crud-api-service
      Cluster: !Ref ECSCluster
      TaskDefinition: !Ref TaskDefinition
      DesiredCount: 1
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          Subnets: !Ref SubnetIds
          SecurityGroups:
            - !Ref ContainerSecurityGroup

  # Grupo de seguridad para el contenedor (puerto 80)
  ContainerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for CRUD API container
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0
          Description: Allow all outbound traffic

  # Grupo de CloudWatch Logs
  CloudWatchLogsGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /ecs/crud-api
      RetentionInDays: 7

Outputs:
  ServiceName:
    Description: Nombre del servicio ECS
    Value: !Ref ECSService
  ClusterName:
    Description: Nombre del cluster ECS
    Value: !Ref ECSCluster
  SecurityGroupId:
    Description: ID del grupo de seguridad del contenedor
    Value: !Ref ContainerSecurityGroup
